### ISSUE TITLE
PGBASENV_EXCLUDE_FILESYSTEMS

### ISSUE THREAD

**Issue by GMOSMAR** [Trivadis/pgbasenv#3]
Hi

I don't know if it is a bug or just a configuration thing.
We are running SUSE SLES15SP2 and we have a very slow NFS mount /uxshare on our server.
On every logon we have to wait for pgsetenv.sh to complete, even if in pgbasenv.conf there is the default setting PGBASENV_EXCLUDE_FILESYSTEMS="nfs tmpfs" our slow NFS mount is searched for an installation.

I can see the find process in another terminal during the login of the postgres user:
find /uxshare -maxdepth 7 -type d ( -name bin -o -name global ) ! ( -fstype nfs -o -fstype tmpfs )

As a workaround I can add our NFS mount to PGBASENV_EXCLUDE_DIRS, but is this the intended way?

Regards
  Franco

**Comment by aychin-tvd** [comment]
Hi,

File system filtering was implemented to filter subdirectories and not top level folders.

But it will make more sense to also include top level mount points if their fstype matches PGBASENV_EXCLUDE_FILESYSTEMS list.

The change is already implemented. You can download current version now.

Thanks for contribution.
