### ISSUE TITLE
Aliases for switching environment are not set, if the alias start with 'db'

### ISSUE THREAD

**Issue by masc-online** [Trivadis/pgbasenv#6]
Hello,

When setting up pgBasEnv in a new environment, I noticed that the aliases for the clusters for changing the environment were not set, although the informations in $PGBASENV_BASE/etc/pgclustertab were correct and the display of the pgup command also displayed the correct data.

It was possible to define and use the aliases manually, but they were deleted again after usage/change of the environment.

After some tests and comparisons with other environments, I noticed that the aliases were not set (or maybe set - unset) if their name began with "db", e.g. "db123i01". If other alias names were used, they were processed correctly. For example "pg123i01" or even "DB123I01" were processed normally.

Unfortunately I couldn't find the part of the script that causes the problem, but maybe the problem description helps a bit.

Greetings, Marian

![pgbasenv-alias-handling](https://user-images.githubusercontent.com/55836744/128172328-81c4a67c-8686-43a4-ac8b-73fa9eceb8d0.png)

**Comment by rolandstirnimann** [comment]
Hello Marian

Thank you for reporting this issue. We can reporduce it and will fix it soon.

Regards
Roland

**Comment by aychin-tvd** [comment]
Hello,

The bug was fixed now. You can download the new version.

Regards
